repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: no-commit-to-branch
        name: Don't commit to the default branch
        args: [--branch, main]
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        types_or: [python, pyi]
        stages: [commit]
        language: system
        entry: poetry run mypy --strict

-   repo: local
    hooks:
    -   id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        types_or: [jupyter]
        stages: [commit]
        language: system
        entry: poetry run jupyter nbconvert --clear-output --ClearMetadataPreprocessor.enabled=True
