name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and Publish Suppy
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: python
          package-name: suppy
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install Poetry
        run: pip install poetry

      - name: Bump package version
        run: poetry version ${{ steps.release-please.outputs.tag_name }}

      - name: Build
        run: poetry build

      - name: Publish to PyPi
        if: ${{ steps.release-please.outputs.release_created }}
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
