name: Test chainstock simulation

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Test with tox
      run: |
        pip install tox
        tox
